### ISSUE TITLE
400 The plain HTTP request was sent to HTTPS port

### ISSUE THREAD

**Issue by rvanlieshout** [Hubs-Foundation/hubs-cloud#376]
**Describe the bug**

curl https://assets.host.name/hubs/assets/stylesheets/admin-8148703bdd3f3bf9a068.css returns:

```
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.27.4</center>
</body>
</html>
```

**To Reproduce**
I've been running this on a local server using nginx and HAProxy, because I was unable to get it working on ipv6 without. I'm quite certain that's because of my lack of experience with Kubernetes.

My nginx has:

```
stream {
  server {
    listen 443;
    listen [::]:443;
    proxy_pass 127.0.0.1:8443;
  }

  server {
    listen 80;
    listen [::]:80;
    proxy_pass 127.0.0.1:8080;
  }
}
```

my kind:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    listenAddress: "127.0.0.1"
  - containerPort: 443
    hostPort: 8443
    listenAddress: "127.0.0.1"
```

my haproxy:
```
controller:
  kind: DaemonSet
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
```

with this setup a gen-ssl worked, so something is valid here.

A curl to the main app redirects to /admin, and that tries to load the CSS. That results in the message above

**Expected behavior**
I think the Ingres configuration in my hcce.yaml now redirects ssl traffic to a non ssl host

**Comment by rvanlieshout** [comment]
@DougReeder, thanks for the tip. I do know what te problem is, but I just don't know how to resolve it yet

The hubs service expects HTTPS traffic on port 8080. The HAProxy Ingress sends out plain http requests to that port

This is the ingress section of my hcce.yaml:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ret
  namespace: hcce
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy.org/response-set-header: |
      access-control-allow-origin "https://werkeninvr.nl"
    haproxy.org/path-rewrite: /api-internal(.*) /_drop_
spec:
  tls:
    - hosts:
        - werkeninvr.nl
      secretName: cert-werkeninvr.nl
    - hosts:
        - assets.werkeninvr.nl
      secretName: cert-assets.werkeninvr.nl
    - hosts:
        - stream.werkeninvr.nl
      secretName: cert-stream.werkeninvr.nl
    - hosts:
        - cors.werkeninvr.nl
      secretName: cert-cors.werkeninvr.nl
  rules:
    - host: werkeninvr.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ret
                port:
                  number: 4001
    - host: assets.werkeninvr.nl
      http:
        paths:
          - path: /files/
            pathType: Prefix
            backend:
              service:
                name: ret
                port:
                  number: 4001
          - path: /http
            pathType: ImplementationSpecific # haproxy's "Begin with"
            backend:
              service:
                name: ret
                port:
                  number: 4001
          - path: /hubs
            pathType: Prefix
            backend:
              service:
                name: hubs
                port:
                  number: 8080
          - path: /spoke
            pathType: Prefix
            backend:
              service:
                name: spoke
                port:
                  number: 8080
    - host: cors.werkeninvr.nl
      http:
        paths:
          - path: /files/
            pathType: Prefix
            backend:
              service:
                name: ret
                port:
                  number: 4001
          - path: /http
            pathType: ImplementationSpecific
            backend:
              service:
                name: ret
                port:
                  number: 4001
          - path: /hubs
            pathType: Prefix
            backend:
              service:
                name: hubs
                port:
                  number: 8080
          - path: /spoke
            pathType: Prefix
            backend:
              service:
                name: spoke
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dialog
  namespace: hcce
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy.org/server-ssl: "true"
    haproxy.org/load-balance: "url_param roomId"
spec:
  tls:
    - hosts:
        - stream.werkeninvr.nl
      secretName: cert-stream.werkeninvr.nl
  rules:
    - host: stream.werkeninvr.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dialog
                port:
                  number: 4443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nearspark
  namespace: hcce
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy.org/path-rewrite: /nearspark/(.*) /\1
spec:
  tls:
    - hosts:
        - cors.werkeninvr.nl
      secretName: cert-cors.werkeninvr.nl
  rules:
    - host: cors.werkeninvr.nl
      http:
        paths:
          - path: /nearspark
            pathType: Prefix
            backend:
              service:
                name: nearspark
                port:
                  number: 5000
---
```

the hubs section:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubs
  namespace: hcce
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubs
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hubs
    spec:
      containers:
        - name: hubs
          image: hubsfoundation/hubs:stable-latest
          imagePullPolicy: IfNotPresent
          env:
            - name: turkeyCfg_thumbnail_server
              value: cors.host.name/nearspark
            - name: turkeyCfg_base_assets_path
              value: https://assets.host.name/hubs/
            - name: turkeyCfg_non_cors_proxy_domains
              value: host.name,assets.host.name,demo.hubsfoundation.org,*.demo.hubsfoundation.org
            - name: turkeyCfg_reticulum_server
              value: host.name
            - name: turkeyCfg_cors_proxy_server
              value: cors.host.name
            - name: turkeyCfg_shortlink_domain
              value: host.name
            - name: turkeyCfg_tier
              value: p1
          livenessProbe:
            httpGet:
              path: https://localhost/healthz
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  name: hubs
  namespace: hcce
  annotations:
    haproxy.org/server-ssl: "true"
spec:
  clusterIP: None
  ports:
    - name: https-hubs
      port: 8080
      targetPort: 8080
  selector:
    app: hubs
```
